### ISSUE TITLE
Is this API active?

### ISSUE THREAD

**Issue by cullanshewfelt** [averdin2/MLB_Stats#1]
Hey man, thanks for the inspiration. Where did you find this API and do you know if it will be actively updated through the next season? Looking for an API to pull game day data with for the next season.

**Comment by averdin2** [comment]
Hey, sorry for the late response. I got the api from this website: https://appac.github.io/mlb-data-api-docs/
To be honest with you, I am not completely sure if it will be actively updated throughout the season as I implemented it during this recent offseason and I am not a contributor to the api. However, I noticed while I was working that it actually updated team rosters during the offseason based on trades so I am assuming that it will be actively updated during the season. I plan on updating my project once the season starts so if you have questions for the 2019 season for sure let me know and I'll get back to you.
